export const games = [
  {
    id: "PictureRounds",
    title: "Picture Rounds",
    label: "Picture Rounds",
    description: "Many question types to keep you entertained",
    descriptionSize: "large",
    image: "/images/GamesSection/GamesCarousel/PictureRounds.jpg",
  },
  {
    id: "Conundrums",
    title: "Conundrums",
    label: "Conundrums",
    description:
      "combining logic with word play",
    descriptionSize: "large",
    image: "/images/GamesSection/GamesCarousel/Conundrums.jpg",
  },
  {
    id: "ImagesAsAnswers",
    title: "Images As Answers",
    label: "Images As Answers",
    description: "Questions for all ages",
    descriptionSize: "large",
    image: "/images/GamesSection/GamesCarousel/ImagesAsAnswers.jpg",
  },
  {
    id: "HumATune",
    title: "HumATune",
    label: "HUM A TUNE, OTHERS GUESS",
    description: "YOU HUM iT, We’ll play it!",
    descriptionSize: "small",
    image: "/images/GamesSection/GamesCarousel/TapThatTune.jpg",
  },
    {
    id: "SkillGames",
    title: "Skill and Timing",
    label: "Skill and Timing",
    description: "Its not just a quiz",
    descriptionSize: "large",
    image: "/images/GamesSection/GamesCarousel/SkillGames.jpg",
  },
  {
    id: "PlayWithYourFace",
    title: "Play With Your Face",
    label: "Play With Your Face",
    description: "Lots of nonsense ( OPEN MOUTH TO JUMP)",
    descriptionSize: "large",
    image: "/images/GamesSection/GamesCarousel/PlayWithYourFace.jpg",
  },
  {
    id: "RealWorldChaos",
    title: "Scavenger Hunt",
    label: "Scavenger Hunt",
    description: "Run around the house! We embrace real world CHAOS!",
    descriptionSize: "large",
    image: "/images/GamesSection/GamesCarousel/RealWorldChaos.jpg",
  },
  {
    id: "GamesOfLuck",
    title: "Luck And Judgement",
    label: "Luck And Judgement",
    description: "Pick a colour",
    descriptionSize: "large",
    image: "/images/GamesSection/GamesCarousel/GamesOfLuck.jpg",
  },
  {
    id: "BonusIntro",
    title: "BonusIntro",
    label: "Bonus Round",
    description: "have a break, sit back, and enjoy some random physics nonsense",
    descriptionSize: "small",
    image: "/images/GamesSection/GamesCarousel/BonusIntro.jpg",
  },
  {
    id: "BonusRounds",
    title: "Bonus Rounds",
    label: "Bonus Rounds",
    description: "Built in catch up mechanics, to help those we maybe do not do so well in the knowledge rounds",
    descriptionSize: "small",
    image: "/images/GamesSection/GamesCarousel/BonusRounds.jpg",
  },
  {
    id: "InstantPlay",
    title: "PhonesAsControllers",
    label: "Phones As Controllers",
    description: "Instant play, zero setup",
    descriptionSize: "large",
    image: "/images/GamesSection/GamesCarousel/PhonesAsControllers.jpg",
  },
  {
    id: "upTo16Players",
    title: "PlaySolo",
    label: "Play Solo",
    description: "Play with family or friends",
    descriptionSize: "Large",
    image: "/images/GamesSection/GamesCarousel/UpTo16Players.jpg",
  },
  {
    id: "PLayInTeams",
    title: "PLayInTeams",
    label: "Or PLay In Teams",
    description: "Doing it with others can be more fun",
    descriptionSize: "Large",
    image: "/images/GamesSection/GamesCarousel/PlayInTeams.jpg",
  },
  {
    id: "BeTheHost",
    title: "BeTheHost",
    label: "Be The Host",
    description: "Nothing says ‘Gameshow’ like waving as you appear, Live video streaming, direct from your phone!",
    descriptionSize: "small",
    image: "/images/GamesSection/GamesCarousel/BeTheHost.jpg",
  },
  {
    id: "players",
    title: "players",
    label: "The Players are the show",
    description: "Always visible players",
    descriptionSize: "Large",
    image: "/images/GamesSection/GamesCarousel/players.jpg",
  },
  {
    id: "balloonPopRound",
    title: "balloonPopRound",
    label: "Poptastic Round Formats",
    description: "Be the first to pop your Balloon!",
    descriptionSize: "Large",
    image: "/images/GamesSection/GamesCarousel/balloonPopRound.jpg",
  },
  {
    id: "QEthingWeeklyPack",
    title: "QEthingWeeklyPack",
    label: "Weekly Quiz",
    description: "Play a new show every week, topical questions",
    descriptionSize: "Large",
    image: "/images/GamesSection/GamesCarousel/QEthingWeeklyPack.jpg",
  },
];