export const games = [
  {
    id: "home",
    title: "Home",
    label: "At Home",
    image: "/images/GamesSection/GamesCarousel/AtHome.jpg",
  },
  {
    id: "bonusRounds",
    title: "Bonus Rounds",
    label: "Bonus Rounds",
    image: "/images/GamesSection/GamesCarousel/BonusRounds.jpg",
  },
  {
    id: "gamesOfLuck",
    title: "Games Of Luck",
    label: "Games of Luck",
    image: "/images/GamesSection/GamesCarousel/GamesOfLuck.jpg",
  },
  {
    id: "madeForTheLivingroom",
    title: "Made For The Livingroom",
    label: "Made for the Livingroom",
    image: "/images/GamesSection/GamesCarousel/MadeFortheLivingRoom.jpg",
  },
  {
    id: "multipleChoice",
    title: "Multiple Choice",
    label: "Multiple Choice",
    image: "/images/GamesSection/GamesCarousel/MultipleChoice.jpg",
  },
  {
    id: "phonesAsControllers",
    title: "Phones As Controllers",
    label: "Phones as Controllers",
    image: "/images/GamesSection/GamesCarousel/PhonesAsControllers.jpg",
  },
  {
    id: "pictureRounds",
    title: "Picture Rounds",
    label: "Picture Rounds",
    image: "/images/GamesSection/GamesCarousel/PictureRounds.jpg",
  },
  {
    id: "playWithYourFace",
    title: "Play With Your Face",
    label: "Play with Your Face",
    image: "/images/GamesSection/GamesCarousel/PlayWithYourFace.jpg",
  },
  {
    id: "realWorldChaos",
    title: "Real World Chaos",
    label: "Real World Chaos",
    image: "/images/GamesSection/GamesCarousel/RealWorldChaos.jpg",
  },
  {
    id: "skillGames",
    title: "Skill Games",
    label: "Skill Games",
    image: "/images/GamesSection/GamesCarousel/SkillGames.jpg",
  },
  {
    id: "solo",
    title: "Solo",
    label: "Solo",
    image: "/images/GamesSection/GamesCarousel/Solo.jpg",
  },
  {
    id: "tapThatTune",
    title: "Tap That Tune",
    label: "Tap That Tune",
    image: "/images/GamesSection/GamesCarousel/TapThatTune.jpg",
  },
  {
    id: "upTo16Players",
    title: "Up To 16 Players",
    label: "Up To 16 Players",
    image: "/images/GamesSection/GamesCarousel/UpTo16Players.jpg",
  },
  {
    id: "wordPlay",
    title: "Word Play",
    label: "Word Play",
    image: "/images/GamesSection/GamesCarousel/WordPlay.jpg",
  },
];